import sbt.Def
import sbt.Tests.{Group, SubProcess}
import uk.gov.hmrc.sbtdistributables.SbtDistributablesPlugin._

lazy val scoverageSettings = {
  import scoverage.ScoverageKeys
  Seq(
    // Semicolon-separated list of regexes matching classes to exclude
    ScoverageKeys.coverageExcludedPackages := """uk\.gov\.hmrc\.BuildInfo;.*\.Routes;.*\.RoutesPrefix;.*Filters?;MicroserviceAuditConnector;Module;GraphiteStartUp;.*\.Reverse[^.]*;uk\.gov\.hmrc\.traderservices\.views\.html\.components\.*""",
    ScoverageKeys.coverageMinimumStmtTotal := 80.00,
    ScoverageKeys.coverageFailOnMinimum := false,
    ScoverageKeys.coverageHighlighting := true
  )
}

lazy val root = (project in file("."))
  .settings(
    name := "trader-services-route-one-frontend",
    organization := "uk.gov.hmrc",
    scalaVersion := "2.12.12",
    PlayKeys.playDefaultPort := 9379,
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.HtmlFormat",
      "uk.gov.hmrc.govukfrontend.views.html.components._",
      "uk.gov.hmrc.traderservices.views.html.components",
      "uk.gov.hmrc.traderservices.views.ViewHelpers._"
    ),
    libraryDependencies ++= AppDependencies(),
    publishingSettings,
    scoverageSettings,
    majorVersion := 0,
    WebpackKeys.outputFileName in WebpackKeys.webpack := "javascripts/application.min.js",
    WebpackKeys.entries in WebpackKeys.webpack := Seq(
      "assets:javascripts/index.ts"
    )
  )
  .configs(IntegrationTest)
  .settings(inConfig(Compile)(compileSettings): _*)
  .settings(inConfig(Test)(testSettings): _*)
  .settings(inConfig(IntegrationTest)(itSettings): _*)
  .settings(
    // silence all warnings on autogenerated files
    scalacOptions += "-P:silencer:pathFilters=target/.*",
    // Make sure you only exclude warnings for the project directories, i.e. make builds reproducible
    scalacOptions += s"-P:silencer:sourceRoots=${baseDirectory.value.getCanonicalPath}",
    libraryDependencies ++= Seq(
      compilerPlugin("com.github.ghik" % "silencer-plugin" % "1.7.1" cross CrossVersion.full),
      "com.github.ghik" % "silencer-lib" % "1.7.1" % Provided cross CrossVersion.full
    )
  )
  .disablePlugins(JUnitXmlReportPlugin) //Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .enablePlugins(PlayScala, SbtDistributablesPlugin)

inConfig(IntegrationTest)(org.scalafmt.sbt.ScalafmtPlugin.scalafmtConfigSettings)

lazy val compileSettings: Seq[Def.Setting[_]] = Seq(
  unmanagedResourceDirectories += baseDirectory.value / "resources",
  scalafmtOnCompile := true
)

lazy val testSettings: Seq[Def.Setting[_]] = Seq(
  javaOptions += "-Djava.locale.providers=CLDR,JRE",
  parallelExecution := false,
  scalafmtOnCompile := true
)

lazy val itSettings: Seq[Def.Setting[_]] =
  Defaults.itSettings ++ Seq(
    Keys.fork := false,
    unmanagedSourceDirectories := Seq(baseDirectory.value / "it"),
    parallelExecution := false,
    testGrouping := oneForkedJvmPerTest((definedTests in IntegrationTest).value),
    javaOptions += "-Djava.locale.providers=CLDR,JRE"
  )

def oneForkedJvmPerTest(tests: Seq[TestDefinition]): Seq[Group] =
  tests.map { test =>
    new Group(test.name, Seq(test), SubProcess(ForkOptions().withRunJVMOptions(Vector(s"-Dtest.name=${test.name}"))))
  }
